
[TILES]
"#" = "WALL"
"." = 'FLOOR'
"*" = '''TILE:ISLAND'''
"=" = """COUNTER"""

[STORE1]
layout = '''
*************
*************
*************
**#########**
**#.......#**
**#=======#**
**#.......#**
**#.......#**
**###...###**
*************
*************
*************
'''
tags = ["STORE"]

[STORE2]
layout = '''
***********
***********
***********
*#########*
*#.......#*
*#=======#*
*#.......#*
*#.......#*
*###...###*
***********
***********
***********
'''
tiles = { "#" = "WALL" }
tags = ["STORE"]

[STORE3]
layout = '''
***********
***********
***********
*#########*
*#.......#*
*#=======#*
*#.......#*
*#.......#*
*###...###*
***********
***********
***********
'''
tags = ["STORE"]

[STORE3.tiles]
"#" = "WALL"
